# Generated by Django 3.2.4 on 2021-06-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonmoy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('work1', models.CharField(max_length=50)),
                ('work2', models.CharField(max_length=50)),
                ('work3', models.CharField(max_length=50)),
                ('work4', models.CharField(max_length=50)),
                ('work5', models.CharField(max_length=50)),
            ],
        ),
    ]
