# Generated by Django 3.2.4 on 2021-06-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonmoy', '0002_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
