# Generated by Django 3.2.4 on 2021-06-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonmoy', '0003_delete_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
