# Generated by Django 3.2.4 on 2021-06-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonmoy', '0004_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('heading_1', models.CharField(max_length=50)),
                ('description_1', models.TextField()),
                ('heading_2', models.CharField(max_length=50)),
                ('description_2', models.TextField()),
                ('heading_3', models.CharField(max_length=50)),
                ('description_3', models.TextField()),
                ('heading_4', models.CharField(max_length=50)),
                ('description_4', models.TextField()),
            ],
        ),
    ]
