# Generated by Django 3.2.4 on 2021-06-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonmoy', '0005_workprocess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workprocess',
        ),
    ]
