# Generated by Django 3.2.4 on 2021-06-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonmoy', '0007_workprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprocess',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
