# Generated by Django 3.2.4 on 2021-06-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonmoy', '0008_workprocess_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
