# Generated by Django 3.2.4 on 2021-06-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonmoy', '0009_delete_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=50)),
                ('jobposition_1', models.CharField(max_length=50)),
                ('description_1', models.TextField()),
                ('jobposition_2', models.CharField(max_length=50)),
                ('description_2', models.TextField()),
                ('jobposition_3', models.CharField(max_length=50)),
                ('description_3', models.TextField()),
                ('jobposition_4', models.CharField(max_length=50)),
                ('description_4', models.TextField()),
                ('date', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
