# Generated by Django 3.2.4 on 2021-06-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonmoy', '0012_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
