# Generated by Django 3.2.4 on 2021-06-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonmoy', '0013_delete_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('school_description', models.TextField()),
                ('school_time', models.IntegerField()),
                ('collage', models.CharField(max_length=50)),
                ('collage_description', models.TextField()),
                ('collage_time', models.IntegerField()),
                ('university', models.CharField(max_length=50)),
                ('university_description', models.TextField()),
                ('university_time', models.IntegerField()),
                ('webdesign', models.CharField(max_length=50)),
                ('webdevelopment', models.CharField(max_length=50)),
                ('web_description', models.TextField()),
                ('web_time', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
